[package]
name = "elf_loader"
version = "0.1.0"
edition = "2021"
authors = ["Haodi Jiang <jhdjames37@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmas-elf = "0.7.0"
memory_addr = { path = "../memory_addr" }
page_table_entry = { path = "../page_table_entry" }