[package]
name = "microkernel-fs-deamon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libax = { path = "../../../ulib/libax_user", package = "libax_user"}
axfs = { path = "../../../modules/axfs", features = ["user"], default-features = true }
syscall_number = { path = "../../../crates/syscall_number"}