[workspace]

members = [
    "apps/display",
    "apps/exception",
    "apps/helloworld",
    "apps/memtest",
    "apps/fs/shell",
    "apps/microkernel/apps",
    "apps/microkernel/init",
    "apps/microkernel/net_deamon",
    "apps/microkernel/tests",
    "apps/microkernel/fs_deamon",
    "apps/net/echoserver",
    "apps/net/httpclient",
    "apps/net/httpserver",
    "apps/net/udpserver",
    "apps/task/parallel",
    "apps/task/sleep",
    "apps/task/yield",
    "apps/task/priority",

    "crates/allocator",
    "crates/arm_gic",
    "crates/axerrno",
    "crates/axfs_devfs",
    "crates/axfs_ramfs",
    "crates/axfs_vfs",
    "crates/axio",
    "crates/capability",
    "crates/crate_interface",
    "crates/driver_block",
    "crates/driver_common",
    "crates/driver_display",
    "crates/driver_net",
    "crates/driver_pci",
    "crates/driver_virtio",
    "crates/elf_loader",
    "crates/flatten_objects",
    "crates/handler_table",
    "crates/kernel_guard",
    "crates/lazy_init",
    "crates/linked_list",
    "crates/memory_addr",
    "crates/page_table",
    "crates/page_table_entry",
    "crates/percpu",
    "crates/percpu_macros",
    "crates/ratio",
    "crates/scheduler",
    "crates/scheme",
    "crates/slab_allocator",
    "crates/spinlock",
    "crates/syscall_number",
    "crates/timer_list",
    "crates/tuple_for_each",

    "modules/axalloc",
    "modules/axconfig",
    "modules/axdisplay",
    "modules/axdriver",
    "modules/axfs",
    "modules/axhal",
    "modules/axlog",
    "modules/axmem",
    "modules/axnet",
    "modules/axprocess",
    "modules/axruntime",
    "modules/axsync",
    "modules/axscheme",
    "modules/axtask",
    "modules/axuser",

    "ulib/libax",
    "ulib/libax_user",
]
