[package]
name = "scheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axerrno = { path = "../axerrno" }
syscall_number = { path = "../syscall_number"}
axfs_vfs = { path = "../axfs_vfs"}