[package]
name = "axuser"
version = "0.1.0"
edition = "2021"
authors = ["Haodi Jiang <jhdjames37@outlook.com>"]
description = "User init program linkage of ArceOS (microkernel version)"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]

# Logging
log-level-off = ["axlog/log-level-off"]
log-level-error = ["axlog/log-level-error"]
log-level-warn = ["axlog/log-level-warn"]
log-level-info = ["axlog/log-level-info"]
log-level-debug = ["axlog/log-level-debug"]
log-level-trace = ["axlog/log-level-trace"]

# Platform
platform-qemu-virt-riscv = ["axhal/platform-qemu-virt-riscv", "axdriver?/bus-mmio"]
platform-qemu-virt-aarch64 = ["axhal/platform-qemu-virt-aarch64", "axdriver?/bus-mmio"]

user-paging = ["axtask/user-paging", "axruntime/user-paging"]
user-net = ["axruntime/user-net"]
user-fs = ["axruntime/user-fs"]
default = ["user-paging"]

[dependencies]

# only including necessary modules for now.
axdriver = { path = "../axdriver", optional = true }
axhal = { path = "../axhal", features = ["user", "paging"] }
axlog = { path = "../axlog" }
axruntime = { path = "../axruntime", features = ["user", "alloc", "paging"
  , "multitask", "irq", "process", "futex"] }
axtask = { path = "../axtask", features = ["irq"]}
axsync = { path = "../axsync", features = ["futex"]}